#!/bin/bash
export VAULT_ADDR='https://vault.techascent.com'
echo "Requesting AWS creds..."
creds=`vault read aws/sts/core`
access_key=$(echo "$creds" | awk '/access_key/ { print $2 }')
secret_key=$(echo "$creds" | awk '/secret_key/ { print $2 }')
security_token=$(echo "$creds" | awk '/security_token/ { print $2 }')
export AWS_ACCESS_KEY_ID=$access_key
export AWS_SECRET_ACCESS_KEY=$secret_key
export AWS_SESSION_TOKEN=$security_token
